package net.opentrends.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Person service. Represents a row in the &quot;portal_Person&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.user.model.impl.PersonModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.user.model.impl.PersonImpl}.
 * </p>
 *
 * @author Ravi
 * @see Person
 * @see net.opentrends.user.model.impl.PersonImpl
 * @see net.opentrends.user.model.impl.PersonModelImpl
 * @generated
 */
public interface PersonModel extends BaseModel<Person>, StagedGroupedModel,
    WorkflowedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a person model instance should use the {@link Person} interface instead.
     */

    /**
     * Returns the primary key of this person.
     *
     * @return the primary key of this person
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this person.
     *
     * @param primaryKey the primary key of this person
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this person.
     *
     * @return the uuid of this person
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this person.
     *
     * @param uuid the uuid of this person
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the person ID of this person.
     *
     * @return the person ID of this person
     */
    public long getPersonId();

    /**
     * Sets the person ID of this person.
     *
     * @param personId the person ID of this person
     */
    public void setPersonId(long personId);

    /**
     * Returns the group ID of this person.
     *
     * @return the group ID of this person
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this person.
     *
     * @param groupId the group ID of this person
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this person.
     *
     * @return the company ID of this person
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this person.
     *
     * @param companyId the company ID of this person
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this person.
     *
     * @return the user ID of this person
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this person.
     *
     * @param userId the user ID of this person
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this person.
     *
     * @return the user uuid of this person
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this person.
     *
     * @param userUuid the user uuid of this person
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this person.
     *
     * @return the user name of this person
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this person.
     *
     * @param userName the user name of this person
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this person.
     *
     * @return the create date of this person
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this person.
     *
     * @param createDate the create date of this person
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this person.
     *
     * @return the modified date of this person
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this person.
     *
     * @param modifiedDate the modified date of this person
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this person.
     *
     * @return the name of this person
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this person.
     *
     * @param name the name of this person
     */
    public void setName(String name);

    /**
     * Returns the sex of this person.
     *
     * @return the sex of this person
     */
    @AutoEscape
    public String getSex();

    /**
     * Sets the sex of this person.
     *
     * @param sex the sex of this person
     */
    public void setSex(String sex);

    /**
     * Returns the age of this person.
     *
     * @return the age of this person
     */
    public int getAge();

    /**
     * Sets the age of this person.
     *
     * @param age the age of this person
     */
    public void setAge(int age);

    /**
     * Returns the city of this person.
     *
     * @return the city of this person
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this person.
     *
     * @param city the city of this person
     */
    public void setCity(String city);

    /**
     * Returns the status of this person.
     *
     * @return the status of this person
     */
    @Override
    public int getStatus();

    /**
     * Sets the status of this person.
     *
     * @param status the status of this person
     */
    @Override
    public void setStatus(int status);

    /**
     * Returns the status by user ID of this person.
     *
     * @return the status by user ID of this person
     */
    @Override
    public long getStatusByUserId();

    /**
     * Sets the status by user ID of this person.
     *
     * @param statusByUserId the status by user ID of this person
     */
    @Override
    public void setStatusByUserId(long statusByUserId);

    /**
     * Returns the status by user uuid of this person.
     *
     * @return the status by user uuid of this person
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getStatusByUserUuid() throws SystemException;

    /**
     * Sets the status by user uuid of this person.
     *
     * @param statusByUserUuid the status by user uuid of this person
     */
    @Override
    public void setStatusByUserUuid(String statusByUserUuid);

    /**
     * Returns the status by user name of this person.
     *
     * @return the status by user name of this person
     */
    @AutoEscape
    @Override
    public String getStatusByUserName();

    /**
     * Sets the status by user name of this person.
     *
     * @param statusByUserName the status by user name of this person
     */
    @Override
    public void setStatusByUserName(String statusByUserName);

    /**
     * Returns the status date of this person.
     *
     * @return the status date of this person
     */
    @Override
    public Date getStatusDate();

    /**
     * Sets the status date of this person.
     *
     * @param statusDate the status date of this person
     */
    @Override
    public void setStatusDate(Date statusDate);

    /**
     * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
     */
    @Override
    public boolean getApproved();

    /**
     * Returns <code>true</code> if this person is approved.
     *
     * @return <code>true</code> if this person is approved; <code>false</code> otherwise
     */
    @Override
    public boolean isApproved();

    /**
     * Returns <code>true</code> if this person is denied.
     *
     * @return <code>true</code> if this person is denied; <code>false</code> otherwise
     */
    @Override
    public boolean isDenied();

    /**
     * Returns <code>true</code> if this person is a draft.
     *
     * @return <code>true</code> if this person is a draft; <code>false</code> otherwise
     */
    @Override
    public boolean isDraft();

    /**
     * Returns <code>true</code> if this person is expired.
     *
     * @return <code>true</code> if this person is expired; <code>false</code> otherwise
     */
    @Override
    public boolean isExpired();

    /**
     * Returns <code>true</code> if this person is inactive.
     *
     * @return <code>true</code> if this person is inactive; <code>false</code> otherwise
     */
    @Override
    public boolean isInactive();

    /**
     * Returns <code>true</code> if this person is incomplete.
     *
     * @return <code>true</code> if this person is incomplete; <code>false</code> otherwise
     */
    @Override
    public boolean isIncomplete();

    /**
     * Returns <code>true</code> if this person is pending.
     *
     * @return <code>true</code> if this person is pending; <code>false</code> otherwise
     */
    @Override
    public boolean isPending();

    /**
     * Returns <code>true</code> if this person is scheduled.
     *
     * @return <code>true</code> if this person is scheduled; <code>false</code> otherwise
     */
    @Override
    public boolean isScheduled();

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Person person);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Person> toCacheModel();

    @Override
    public Person toEscapedModel();

    @Override
    public Person toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
